In [1]:
import pandas as pd

###`Q-1:` You are given a Multi index DataFrame. You task is to swap level-0 index with level-0 column.
* Change Branch -> ('cse', 'ece') as columns at level-0 and ('delhi'	'mumbai') as level-0 Index
* And Sort on row index level-0

In [2]:
# Given Code Snippets
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
df = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multiindex,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

df

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [5]:
df.unstack()

          delhi                                             mumbai            \
    avg_package                students                avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           1    3    5    7        2    4    6    8           0    0    0
ece           9   11   13   15       10   12   14   16           0    0    0


         students
    2022     2019 2020 2021 2022
cse    0        0    0    0    0
ece    0        0    0    0    0

In [6]:
# step 1
df.unstack(level=0)

           delhi                       mumbai
     avg_package     students     avg_package     students
             cse ece      cse ece         cse ece      cse ece
2019           1   9        2  10           0   0        0   0
2020           3  11        4  12           0   0        0   0
2021           5  13        6  14           0   0        0   0
2022           7  15        8  16           0   0        0   0

In [7]:
#  step 2
df.unstack(level=0).stack(level=0)

/tmp/ipykernel_10235/268355546.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.unstack(level=0).stack(level=0)

            avg_package     students
                    cse ece      cse ece
2019 delhi            1   9        2  10
     mumbai           0   0        0   0
2020 delhi            3  11        4  12
     mumbai           0   0        0   0
2021 delhi            5  13        6  14
     mumbai           0   0        0   0
2022 delhi            7  15        8  16
     mumbai           0   0        0   0

In [11]:
#  step 3
df.unstack(level=0).stack(level=0).swaplevel()

/tmp/ipykernel_10235/2942742932.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.unstack(level=0).stack(level=0).swaplevel()

            avg_package     students
                    cse ece      cse ece
delhi  2019           1   9        2  10
mumbai 2019           0   0        0   0
delhi  2020           3  11        4  12
mumbai 2020           0   0        0   0
delhi  2021           5  13        6  14
mumbai 2021           0   0        0   0
delhi  2022           7  15        8  16
mumbai 2022           0   0        0   0

In [12]:
#  step 4
df.unstack(level=0).stack(level=0).swaplevel().swaplevel(axis=1)

/tmp/ipykernel_10235/120224511.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.unstack(level=0).stack(level=0).swaplevel().swaplevel(axis=1)

                    cse         ece      cse      ece
            avg_package avg_package students students
delhi  2019           1           9        2       10
mumbai 2019           0           0        0        0
delhi  2020           3          11        4       12
mumbai 2020           0           0        0        0
delhi  2021           5          13        6       14
mumbai 2021           0           0        0        0
delhi  2022           7          15        8       16
mumbai 2022           0           0        0        0

In [13]:
#  step 5
df.unstack(level=0).stack(level=0).swaplevel().swaplevel(axis=1).sort_index()

/tmp/ipykernel_10235/336930679.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.unstack(level=0).stack(level=0).swaplevel().swaplevel(axis=1).sort_index()

                    cse         ece      cse      ece
            avg_package avg_package students students
delhi  2019           1           9        2       10
       2020           3          11        4       12
       2021           5          13        6       14
       2022           7          15        8       16
mumbai 2019           0           0        0        0
       2020           0           0        0        0
       2021           0           0        0        0
       2022           0           0        0        0

###`Q-2:` Covid Cases Data Set Problem
 Make a DataFrame Using both Covid Dataset. With Country name as Level-0 and Provinance/State as Level-1 Index and date, No of cases and No of Deaths as Columns.

In [19]:
confirm = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTmqT3kxd0i0RUFiEnwA1Hboiunv28MeNTatZsIEqlPPB7mHrl0ttJL7utZ23_1s5FW8ZjODmB8jHIi/pub?gid=2142019845&single=true&output=csv')

deaths = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQn4nLCKIVZMw4e89YeRqgKaSAAwRFaZ6ILMW_FUejZ2tkv3Np1f9gD4QOl3ASHeLzWjOjfmLDKcCOF/pub?gid=212966958&single=true&output=csv")

In [15]:
deaths.head(2)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595

In [20]:
deaths = deaths.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_deaths')
confirm = confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_cases')

In [21]:
deaths

,Province/State,Country/Region,Lat,Long,date,num_deaths
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,5637

In [25]:
final_df = confirm.merge(deaths,on=['Province/State','Country/Region','Lat','Long','date'])
final_df

,Province/State,Country/Region,Lat,Long,date,num_cases,num_deaths
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0,0
...,...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981,5637

In [26]:
final_df.set_index(['Country/Region','Province/State'],inplace=True)
final_df = final_df[['date','num_cases','num_deaths']]
final_df

                                        date  num_cases  num_deaths
Country/Region       Province/State
Afghanistan          NaN             1/22/20          0           0
Albania              NaN             1/22/20          0           0
Algeria              NaN             1/22/20          0           0
Andorra              NaN             1/22/20          0           0
Angola               NaN             1/22/20          0           0
...                                      ...        ...         ...
West Bank and Gaza   NaN              1/2/23     703228        5708
Winter Olympics 2022 NaN              1/2/23        535           0
Yemen                NaN              1/2/23      11945        2159
Zambia               NaN              1/2/23     334661        4024
Zimbabwe             NaN              1/2/23     259981        5637

[311253 rows x 3 columns]

###`Q-3:` Show Country with Highest death percent out of confirmed Cases.

In [ ]:
# code here
temp_df = final_df.groupby('Country/Region').sum()
temp_df['death_percentage'] = (temp_df['num_deaths']/temp_df['num_cases'])*100
temp_df.sort_values('death_percentage',ascending=False)